import {StyleSheet} from 'react-native';
import colors from '../components/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: colors.background,
  },
  textInput: {
    height: 50,
    borderRadius: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.lighgray,
    marginBottom: 10,
    paddingHorizontal: 40,
    color: 'black',
  },
  textInputIcon: {
    position: 'absolute',
    bottom: 25,
    left: 10,
  },
  button: {
    backgroundColor: colors.purple,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    marginTop: 20,
  },
  buttonText: {
    color: 'white',
    fontWeight: '800',
  },
  leadIMG: {
    width: 200,
    height: 200,
    alignSelf: 'center',
  },
  text: {
    fontFamily: 'SourceSansPro-Regular',
    color: 'black',
  },
  heading: {
    // fontFamily: 'SourceSansPro-Bold',
    color: 'gray',
    fontSize: 25,
    fontWeight: '900',
    marginLeft: 20,
  },
  textLink: {
    fontFamily: 'SourceSansPro-Bold',
    color: colors.lightPurple,
  },
  shortLine: {
    borderWidth: 1,
    borderColor: colors.lighgray,
    width: '10%',
    alignSelf: 'center',
    marginVertical: 40,
  },
  longLine: {
    borderWidth: 1,
    borderColor: colors.lighgray,
    width: '100%',
    alignSelf: 'center',
  },
  textContainer: {
    alignItems: 'center',
    marginTop: 10,
  },
  subHeading: {
    fontFamily: 'SourceSansPro-Bold',
    color: colors.lightPurple,
    fontSize: 18,
  },
  logoIMG: {
    width: '100%',
    height: '100%',
  },
  logoIMGContainer: {
    height: 45,
    width: 50,
  },
  balanceContainer: {
    height: 150,
    borderRadius: 20,
    flex: 1,
    shadowColor: 'black',
    shadowOffset: {
      height: 5,
      width: 5,
    },
    shadowOpacity: 0.9,
    shadowRadius: 50,
    elevation: 5,
  },
  actionContainer: {
    height: 150,
    width: '30%',
    backgroundColor: colors.lightPurple,
    borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: {
      height: 5,
      width: 5,
    },
    shadowOpacity: 0.9,
    shadowRadius: 5,
    elevation: 5,
  },
  majorActionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 20,
  },
  actionImageContainer: {
    width: 60,
    height: 60,
    padding: 10,
    borderRadius: 35,
    backgroundColor: 'white',
    borderWidth: 2,
    borderColor: colors.lighgray,
  },
  actionImage: {
    width: '100%',
    height: '100%',
  },
  actionText: {
    color: 'white',
    marginTop: 20,
    fontSize: 16,
    fontFamily: 'SourceSansPro-Bold',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    backgroundColor: 'rgba(0,0,0,0.9)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    alignItems: 'center',
    width: 350,
    height: 350,
    justifyContent: 'center',
    shadowColor: 'white',
    shadowOffset: {
      width: 10,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 5,
  },
  modalInput: {
    borderRadius: 10,
    shadowColor: 'black',
    shadowOffset: {height: 5, width: 5},
    shadowRadius: 5,
    shadowOpacity: 0.1,
    elevation: 10,
    backgroundColor: '#e6e6ff',
    height: 50,
    padding: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: 'black',
    width: '80%',
    marginTop: 20,
  },
  miBG: {
    alignItems: 'center',
    shadowColor: 'black',
    padding: 10,
    flex: 1,
    borderRadius: 10,
  },
});

export default styles;
